const data = {
    products:[
        {
            _id:'1',
            name: "Nike Slim Shirt",
            categoty: "shirt",
            image: '/images/products/p1.jpeg',
            price:120,
            brand: "Nike", 
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: "Addidas fit Shirt",
            categoty: "shirt",
            image: '/images/products/p2.jpeg',
            price:130,
            brand: "Addidas", 
            rating: 4,
            numReviews: 7,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: "Raymond Free Shirt",
            categoty: "shirt",
            image: '/images/products/p3.jpeg',
            price:170,
            brand: "Raymond", 
            rating: 4.7,
            numReviews: 12,
            description: 'Raymond best quality product',
        },
        {
            _id:'3',
            name: "Addidas fit pants",
            categoty: "pants",
            image: '/images/products/p4.jpeg',
            price:250,
            brand: "Addidas", 
            rating: 4.1,
            numReviews: 5,
            description: 'best addidas quality product',
        },
        {
            _id:'5',
            name: "Nike fit pant combo",
            categoty: "Pants",
            image: '/images/products/p5.jpeg',
            price:520,
            brand: "Nike", 
            rating: 4.5,
            numReviews: 10,
            description: 'Most liked product',
        },

        {
            _id:'6',
            name: "Addidas fit pant",
            categoty: "Pants",
            image: '/images/products/p6.jpeg',
            price:220,
            brand: "Addidas", 
            rating: 4.7,
            numReviews: 5,
            description: 'nice best formal quality product',
        },
    ]
}
export default data;